### ISSUE TITLE
Payment support in Apps

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-template-dotnet#15]
## Description

In Altinn 2 we support integrating payment as part of the service process. 

To move the services from Altinn 2 we need payment support.

## Consideration

- How do we store payment info?
- Do we need a payment component?
- Common payment "app" for non Altinn App scenarios. 
- Which providers should we support (Payex, dips, Nets...) 
- Role requirement payment? 
- Process integration
- No fixed URL in apps? Is this ok as a return URL or not?

## 

**Tasks**
- [ ] Verify that this issue is labeled with a correct area label.
- [ ] QA has been done

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/334
```

**Comment by olavflar** [comment]
Link to the Miroboard where design work: https://miro.com/app/board/uXjVMYz1128=/?share_link_id=865780642344

**Comment by olavflar** [comment]
Comments/ Feedback on this sketch?

![Image](https://github.com/Altinn/app-template-dotnet/assets/70377508/69afb8a1-53f4-4ca7-9310-48cff5e99592)

**Comment by olavflar** [comment]
For mobile:

![Image](https://github.com/Altinn/app-template-dotnet/assets/70377508/ba04b139-d248-4599-acca-2001924107e7)

**Comment by tjololo** [comment]
Closing this as newer design images are present in https://github.com/Altinn/app-lib-dotnet/issues/399 and other work is tracked through that issue

**Comment by tjololo** [comment]
Closing this as newer design images are present in https://github.com/Altinn/app-lib-dotnet/issues/399 and other work is tracked through that issue (correct status)
