### ISSUE TITLE
Add support for new PDF Service

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-template-dotnet#154]
### Description

Add support for new PDF Service which accepts a url to the page to be rendered as the PDF receipt.

### Additional Information

Epic: https://github.com/Altinn/app-lib-dotnet/issues/63
Frontend: https://github.com/Altinn/app-frontend-react/issues/710

### Tasks

- [ ] Implement support for the new PDF service
- [ ] Consider feature toggling the new PDF service
- [ ] Ensure the data is not locked in case the PDF generation fails (could/should be solved by making the call to platform idempotent ie. it should be possible to lock a already locked data element)
- [ ] Add support for running the new PDF Service in LocalTest
