### ISSUE TITLE
Support for User controlled signing in App template

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-template-dotnet#17]
## Description

Some services are built in a way that who is the right person to sign the form is specified by the person filling in the form. We need to allow this pattern for apps in Altinn 3.

## Consideration

When moving to the signing task the user that needs to sign needs to be delegated the rights to do this. This require integration with the authorization component

## Acceptance criteria

- Data from form needs to be used to decide who needs to sign
- Users need to be delegated the needed rights to sign
- Process cant be moved forward before all needed signatures is added

**Tasks**
- [ ] Verify that this issue is labeled and written correctly (remove unused stuff, add missing stuff, verify tasks). DoP.
- [ ] Documentation (if relevant)
- [ ] Test / QA (if relevant)
