### ISSUE TITLE
Implementering - Samhandlingstjeneste

### ISSUE THREAD

**Issue by RonnyB71** [Altinn/app-template-dotnet#196]
### Description

.

### Gjennomføring
```[tasklist]
### Oppgaver
- [ ] https://github.com/Altinn/app-frontend-react/issues/265
- [ ] https://github.com/Altinn/app-template-dotnet/issues/25
- [ ] https://github.com/Altinn/app-frontend-react/issues/344
```
