### ISSUE TITLE
Restructure App template

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-template-dotnet#20]
## Introduction

We have several issues related to the App template. This epic will cover 

### Separate template into a new repository

We should create a new git repository for App temples.   Suggestion: Altinn.AppTemplates 

The folder structure should consider that in the future we will see several types of app templates based on technology and on usage. 

- [x] Create repository
- [x] Define and land folder structure
- [x] Copy backend code from the original repository. Make note of when. Manual merge will be required for changes on the template. 
- [ ] Post info about template changes and people should hold off making a pull request for backend
- [ ] Set up the build pipeline for backend in the new repository (Github action?)
- [ ] Move frontend code. This needs to be done when all 
- [ ] Setup build pipeline for app template

### Upgrade backend to .Net 6

In addition, to upgrade .Net 6 we should look into if there are some improvements to C#10 we should take advantage of. 

[C# 10 changes](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10)

- [ ] Change .Net 6
- [ ] Change docker/build setup for .Net 6
- [ ] Upgrade C#10 areas like global namespace 

#### Altinn.App.Api
- Contains all controllers like today

#### Altinn.App.Core

Combines Altinn.App.Common and Altinn.App.Platform

- Process functionality like BPMN Reader
- Business logic like AppBase
- Interface for Business services
- Implementation of Business services
- Interface for PlatformClients

#### Altinn.App.PlatformClients

- Only HTTP client for the different platform interfaces. 

This makes it easier to replace Altinn.Platform partial or fully by other components

### Change how Designer have access to template files

In the current setup, we do copy all template files inn to the designer file structure when e new version of the template should be used in-app. Can we find a better way to do this?

- NuGet package with template files?
- Direct download from app template folder?

## Out of scope

- Frontend restructure.

**Comment by tjololo** [comment]
This is as far as I knonw done. Closing issue
