### ISSUE TITLE
Set up analyze pipeline/github action for app template

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-template-dotnet#4]
## Description

Create analyze pipleine in Azure devops or Github action

## Considerations
- [ ] Failed unit tests does not result in comment on PR, is this ok? 

## Tasks
- [x] Set up workflow
- [x] Configure actions for pr from forks

## Test
- [x] Fork workflow fails if invalid test
- [x] Fork workflow produces comment if all is ok
- [x] Contributer workflow fails i failed test
- [x] Contributer workflow sends results to sonarcloud
